% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%

\documentclass[]{article}
\usepackage{graphicx, enumitem, cancel, fancyhdr, float} 
\usepackage[a4paper, margin=1.25in]{geometry}
\pagestyle{fancy}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}


\setlength{\headheight}{15pt}
\lhead{2nd Sem, A.Y. 2024-2025}
\chead{Stat 138: Problem Set 5}
\rhead{Amores}

\title{Stat 138: Introduction to Sampling Designs \\ Problem Set 5}
\author{Anne Christine Amores}
\date{May 2, 2025}

\makeatletter
\newcommand{\skipitems}[1]{%
  \addtocounter{\@enumctr}{#1}%
}
\makeatother

\begin{document}
\maketitle

\section{IPUMS}\label{ipums}

\subsection{(a) Select an unequal-probability sample of 10 psus, with
probability proportional to number of persons. Take a subsample of 20
persons in each of the selected
psus.}\label{a-select-an-unequal-probability-sample-of-10-psus-with-probability-proportional-to-number-of-persons.-take-a-subsample-of-20-persons-in-each-of-the-selected-psus.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Loading the necessary packages}
\FunctionTok{library}\NormalTok{(readxl)}
\FunctionTok{library}\NormalTok{(survey)}
\end{Highlighting}
\end{Shaded}


\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Importing the dataset}
\NormalTok{ipums }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"ipums.xlsx"}\NormalTok{, }\AttributeTok{col\_names =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Renaming columns}

\FunctionTok{colnames}\NormalTok{(ipums) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"stratum"}\NormalTok{, }\StringTok{"psu"}\NormalTok{, }\StringTok{"inctot"}\NormalTok{, }\StringTok{"age"}\NormalTok{, }\StringTok{"sex"}\NormalTok{, }\StringTok{"race"}\NormalTok{, }
                     \StringTok{"hispanic"}\NormalTok{, }\StringTok{"marstat"}\NormalTok{, }\StringTok{"ownershg"}\NormalTok{, }\StringTok{"yrsusa"}\NormalTok{, }\StringTok{"school"}\NormalTok{, }
                     \StringTok{"educrec"}\NormalTok{, }\StringTok{"labforce"}\NormalTok{, }\StringTok{"occ"}\NormalTok{, }\StringTok{"sei"}\NormalTok{, }\StringTok{"classwk"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(ipums)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 16
##   stratum   psu inctot   age   sex  race hispanic marstat ownershg yrsusa 
##     <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl>    <dbl>   <dbl>    <dbl>  <dbl>  
## 1       1     1   4105    18     1     2        0       5        0      0      
## 2       1     1   7795    20     1     1        0       5        2      0      
## 3       1     1  16985    24     1     1        0       1        1      0      
## 4       1     1   7045    21     1     1        0       1        2      0      
## 5       1     1   2955    23     1     1        0       5        2      0      
## 6       1     1      0    17     1     1        0       5        1      0      
## # i 6 more variables: school <dbl>, educrec <dbl>, labforce <dbl>, occ <dbl>, 
## #   sei <dbl>, classwk <dbl>
\end{verbatim}

\vspace{0.5em}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Getting PSU sizes }
\NormalTok{psu\_sizes }\OtherTok{\textless{}{-}}\NormalTok{ ipums }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(psu) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{M\_i =} \FunctionTok{n}\NormalTok{(), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\CommentTok{\# no. of people in each PSU}

\CommentTok{\# Selecting 10 PSUs via PPSWOR using Brewer\textquotesingle{}s Method}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{138}\NormalTok{)}

\NormalTok{pik  }\OtherTok{\textless{}{-}} \FunctionTok{inclusionprobabilities}\NormalTok{(psu\_sizes}\SpecialCharTok{$}\NormalTok{M\_i, }\DecValTok{10}\NormalTok{)}

\NormalTok{selected\_psu\_indices }\OtherTok{\textless{}{-}} \FunctionTok{UPbrewer}\NormalTok{(pik)}

\NormalTok{psu\_sample }\OtherTok{\textless{}{-}}\NormalTok{ psu\_sizes[selected\_psu\_indices }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, ] }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{pi\_h =}\NormalTok{ pik[selected\_psu\_indices }\SpecialCharTok{==} \DecValTok{1}\NormalTok{])}

\CommentTok{\# Selecting 20 persons per selected PSU via SRSWOR}
\NormalTok{sampled\_people }\OtherTok{\textless{}{-}}\NormalTok{ ipums }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(psu }\SpecialCharTok{\%in\%}\NormalTok{ psu\_sample}\SpecialCharTok{$}\NormalTok{psu) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(psu) }\SpecialCharTok{\%\textgreater{}\%} 
      \FunctionTok{slice\_sample}\NormalTok{(}\AttributeTok{n =} \DecValTok{20}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
        \FunctionTok{ungroup}\NormalTok{()}

\FunctionTok{print}\NormalTok{(sampled\_people)     }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 200 x 16
##    stratum   psu inctot   age   sex  race hispanic marstat ownershg yrsusa
##      <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl>    <dbl>   <dbl>    <dbl>  <dbl>
##  1       1     3   6470    71     1     1        0       4        1      0
##  2       1     3   6005    75     2     1        0       4        1      0
##  3       1     3  15840    44     1     1        0       1        1      0
##  4       1     3      0    15     1     1        0       5        1      0
##  5       1     3   5910    62     2     1        0       1        2      0
##  6       1     3      0    55     2     1        0       1        1      0
##  7       1     3   2110    32     2     2        0       5        2      0
##  8       1     3   8005    46     2     1        0       1        1      0
##  9       1     3   6060    29     2     2        0       1        2      0
## 10       1     3  21005    39     1     2        0       3        1      0
## # i 190 more rows
## # i 6 more variables: school <dbl>, educrec <dbl>, labforce <dbl>, occ <dbl>,
## #   sei <dbl>, classwk <dbl>
\end{verbatim}

The table above gives a preview of our final sample of 200 people.

\subsection{\texorpdfstring{(b) Using the sample you selected, estimate
the population mean and total of \emph{inctot} and give the standard
errors of your
estimates.}{(b) Using the sample you selected, estimate the population mean and total of inctot and give the standard errors of your estimates.}}\label{b-using-the-sample-you-selected-estimate-the-population-mean-and-total-of-inctot-and-give-the-standard-errors-of-your-estimates.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Computing weights }
\NormalTok{sampled\_people }\OtherTok{\textless{}{-}}\NormalTok{ sampled\_people }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{left\_join}\NormalTok{(psu\_sample, }\AttributeTok{by =} \StringTok{"psu"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{weight =}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{/}\NormalTok{ pi\_h) }\SpecialCharTok{*}\NormalTok{ (M\_i }\SpecialCharTok{/} \DecValTok{20}\NormalTok{)) }\CommentTok{\# final weight: stage 1 * stage 2}

\CommentTok{\# Defining survey design }
\NormalTok{unequalprobdesign }\OtherTok{\textless{}{-}} \FunctionTok{svydesign}\NormalTok{(}
  \AttributeTok{id =} \SpecialCharTok{\textasciitilde{}}\NormalTok{psu, }
  \AttributeTok{weights =} \SpecialCharTok{\textasciitilde{}}\NormalTok{weight, }
  \AttributeTok{data =}\NormalTok{ sampled\_people)}

\CommentTok{\# Estimating population mean and standard error }
\NormalTok{inctot\_mean }\OtherTok{\textless{}{-}} \FunctionTok{svymean}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{inctot, unequalprobdesign)}

\CommentTok{\# Estimating population total and standard error}
\NormalTok{inctot\_total }\OtherTok{\textless{}{-}} \FunctionTok{svytotal}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{inctot, unequalprobdesign)}

\newpage 
\NormalTok{inctot\_mean}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          mean     SE
## inctot 7807.2 625.94
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{inctot\_total}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            total       SE
## inctot 417380719 33463183
\end{verbatim}

Thus, given this sample, \textbf{our estimate for the population mean is 7,807.2 and its standard error is 625.94. Our estimate for the population total is 417,380,719 and its standard error is 33,463,183.}
\end{document}
